name: Frontend-Check

on:
  pull_request:
    branches: [ develop, main ]

  workflow_dispatch:

jobs:
  App:
    runs-on: ubuntu-latest
    steps:
      - name: "⚡ Checkout"
        uses: actions/checkout@v3
        
      - name: Codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378
        uses: codecov/codecov-action@v3.1.0
        with:
        # Repository upload token - get it from codecov.io. Required only for private repositories
          token: 6aa901bb-7bc5-4b18-90fd-3aedab16975d # optional
        # Comma-separated list of files to upload
          files: # optional
        # Directory to search for coverage reports.
          directory: # optional
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
          flags: # optional
        # The commit SHA of the parent for which you are uploading coverage. If not present, the parent will be determined using the API of your repository provider.  When using the repository providers API, the parent is determined via finding the closest ancestor to the commit.
          commit_parent: # optional
        # Don't upload files to Codecov
          dry_run: # optional
        # Environment variables to tag the upload with (e.g. PYTHON | OS,PYTHON)
          env_vars: # optional
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
          fail_ci_if_error: # optional
        # Path to coverage file to upload
          file: # optional
        # Comma-separated list, see the README for options and their usage
          functionalities: # optional
        # Run with gcov support
          gcov: # optional
        # Extra arguments to pass to gcov
          gcov_args: # optional
        # Paths to ignore during gcov gathering
          gcov_ignore: # optional
        # Paths to include during gcov gathering
          gcov_include: # optional
        # Move discovered coverage reports to the trash
          move_coverage_to_trash: # optional
        # User defined upload name. Visible in Codecov UI
          name: # optional
        # Specify the branch name
          override_branch: # optional
        # Specify the build number
          override_build: # optional
        # Specify the commit SHA
          override_commit: # optional
        # Specify the pull request number
          override_pr: # optional
        # Specify the git tag
          override_tag: # optional
        # Override the assumed OS. Options are alpine | linux | macos | windows.
          os: # optional
        # Used when not in git/hg project to identify project root directory
          root_dir: # optional
        # Specify the slug manually (Enterprise use)
          slug: # optional
        # Change the upload host (Enterprise use)
          url: # optional
        # Specify whether the Codecov output should be verbose
          verbose: # optional
        # Specify which version of the Codecov Uploader should be used. Defaults to `latest`
          version: # optional
        # Directory in which to execute codecov.sh
          working-directory: # optional
        # Run with xcode support
          xcode: # optional
        # Specify the xcode archive path. Likely specified as the -resultBundlePath and should end in .xcresult
          xcode_archive_path: # optional

      - name: "🧪 Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: "📦 Install Dependencies App"
        working-directory: ./Frontend/Voting App/VoteVault
        run: npm install

#       - name: "🌹 Format Code"
#         working-directory: ./Frontend/Voting App/VoteVault
#         run: yarn format

#       - name: "🧶 Lint Code"
#         working-directory: ./Frontend/Voting App/VoteVault
#         run: npm lint

      - name: "✅ Run Unit Tests App"
        working-directory: ./Frontend/Voting App/VoteVault
        run: npm test
        
      - name: Upload coverage reports to Codecov
        run: |
          # Replace `linux` below with the appropriate OS
          # Options are `alpine`, `linux`, `macos`, `windows`
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
  Website:
    runs-on: ubuntu-latest

    steps:
      - name: "⚡ Checkout"
        uses: actions/checkout@v3
        
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0

      - name: "🧪 Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
        
      - name: "📦 Install Dependencies Website"
        working-directory: ./Frontend/Website/Vote-Vault-Website
        run: npm install
        
      - name: "✅ Run Unit Tests Website"
        working-directory: ./Frontend/Website/Vote-Vault-Website
        run: npm test
        
      - name: "✅ Building"
        working-directory: ./Frontend/Website/Vote-Vault-Website
        run: npm run build

      - name: Upload coverage reports to Codecov
        run: |
          # Replace `linux` below with the appropriate OS
          # Options are `alpine`, `linux`, `macos`, `windows`
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
