name: Frontend-test-Commit-CODECOV

on: [push]

jobs:
  App:
    runs-on: ubuntu-latest
    steps:
      - name: "⚡ Checkout"
        uses: actions/checkout@v3

      - name: "🧪 Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: "📦 Install Dependencies App"
        working-directory: ./Frontend/Voting App/VoteVault
        run: npm install

#       - name: "🧶 Lint Code"
#         working-directory: ./Frontend/Voting App/VoteVault
#         run: npm run lint

      - name: "✅ Run Unit Tests App"
        working-directory: ./Frontend/Voting App/VoteVault
        run: npm test
        
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  Website:
    runs-on: ubuntu-latest

    steps:
      - name: "⚡ Checkout"
        uses: actions/checkout@v3
        
      - name: "🧪 Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
        
      - name: "📦 Install Dependencies Website"
        working-directory: ./Frontend/Website/Vote-Vault-Website
        run: npm install
        
      - name: "✅ Run Unit Tests Website"
        working-directory: ./Frontend/Website/Vote-Vault-Website
        run: npm test
        
      - name: "✅ Building"
        working-directory: ./Frontend/Website/Vote-Vault-Website
        run: npm run build

      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

