name: Frontend-Check

on:
  pull_request:
    branches: [ develop, main ]

  workflow_dispatch:

jobs:
  App:
    runs-on: ubuntu-latest
    steps:
      - name: "⚡ Checkout"
        uses: actions/checkout@v3
        
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0

      - name: "🧪 Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: "📦 Install Dependencies App"
        working-directory: ./Frontend/Voting App/VoteVault
        run: npm install

#       - name: "🌹 Format Code"
#         working-directory: ./Frontend/Voting App/VoteVault
#         run: yarn format

#       - name: "🧶 Lint Code"
#         working-directory: ./Frontend/Voting App/VoteVault
#         run: npm lint

      - name: "✅ Run Unit Tests App"
        working-directory: ./Frontend/Voting App/VoteVault
        run: npm test
        
      - name: Upload coverage reports to Codecov
        run: |
          # Replace `linux` below with the appropriate OS
          # Options are `alpine`, `linux`, `macos`, `windows`
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${6aa901bb-7bc5-4b18-90fd-3aedab16975d}
  Website:
    runs-on: ubuntu-latest

    steps:
      - name: "⚡ Checkout"
        uses: actions/checkout@v3
        
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0

      - name: "🧪 Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
        
      - name: "📦 Install Dependencies Website"
        working-directory: ./Frontend/Website/Vote-Vault-Website
        run: npm install
        
      - name: "✅ Run Unit Tests Website"
        working-directory: ./Frontend/Website/Vote-Vault-Website
        run: npm test
        
      - name: "✅ Building"
        working-directory: ./Frontend/Website/Vote-Vault-Website
        run: npm run build

      - name: Upload coverage reports to Codecov
        run: |
          # Replace `linux` below with the appropriate OS
          # Options are `alpine`, `linux`, `macos`, `windows`
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${6aa901bb-7bc5-4b18-90fd-3aedab16975d}
